#!/bin/sh
#
# chkconfig: 2345 90 10
#
# Custom script for managing the reports mongodb.
# This abstracts away starting/stopping the mongod instance used for reports.

#
# TODO(benkomalo): update the following info for Ubuntu machines
# To have the mongo processes start automatically (as root), copy this
# file into /etc/init.d, and run:
# $ sudo chkconfig --add mongo_cntrl
#
# From then on, it will start on reboot, and can be managed using
# sudo service mongo_cntrl (restart|start|stop)
#

PIDFILE=$HOME/logs/mongo/reportsmongo.pid

start() {
    mkdir -p $HOME/logs/mongo
    mkdir -p $HOME/data/mongo
    echo "Starting mongodb on default port with dbpath $HOME/data/mongo"
    # Note - default mongo port 27017
    mongod --fork \
        --rest \
        --jsonp \
        --dbpath "$HOME/data/mongo" \
        --logpath "$HOME/logs/mongo/mongo.log"

    # Extract PID from logfile after the server starts up
    sleep 1
    head -1 $HOME/logs/mongo/mongo.log | \
        grep -o 'pid=[0-9]\+' | \
        cut -d= -f 2 \
        > $PIDFILE
}
stop() {
    [ -f $PIDFILE ] && ( kill `cat $PIDFILE` 2> /dev/null )
    rm -f $PIDFILE 2> /dev/null
}
restart() {
  stop
  start
}
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    echo "Does not apply"
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    restart
    ;;
  reload)
    restart
    ;;
  force-reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
    exit 2
esac

exit $?

